version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
      exclude-functions:
        - (io.Closer).Close
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*database/sql.Stmt).Close
        - (*database/sql.Tx).Rollback
        - (net.Conn).Close
        - (net.Listener).Close
        - (*net/smtp.Client).Close
        - (*github.com/gorilla/websocket.Conn).Close
        - os.Setenv
        - os.Unsetenv
        - (*bufio.Writer).Flush
        - fmt.Fprintf
        - fmt.Fprint
        - fmt.Fprintln
  exclusions:
    paths:
      - vendor
    rules:
      - path: _test\.go
        linters:
          - errcheck
